### ISSUE TITLE
[MAIN] Find some assets

### ISSUE THREAD

**Issue by crimsonshade** [crimsonshade/minijam-99#1]
# TODO List
- [ ] Find assets for birds
- [ ] Find assets for the area
- [ ] Find assets for the nest/menu
